#gpted
name: Minecraft Source

on:
  schedule:
    - cron: "0 3 * * *"  # runs daily at 3 AM UTC
  workflow_dispatch:      # allows manual runs too

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Get latest Minecraft version
        id: get_version
        run: |
          echo "Fetching latest Minecraft version..."
          VERSION=$(curl -s https://launchermeta.mojang.com/mc/game/version_manifest.json | jq -r '.latest.release')
          echo "Latest Minecraft version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Run update script
        run: |
          echo "Running source.py..."
          python3 ./buildtools/source.py

      - name: Commit and push changes
        if: ${{ success() }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git diff --cached --quiet && echo "No changes to commit." || \
          (git commit -m "${{ steps.get_version.outputs.version }}" && git push)
